import { createServer } from "node:http";
import { randomBytes, timingSafeEqual, createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import { normalizeJob } from "./job-protocol.mjs";
import { createOperator, OperatorError, requireFreshReport } from "./operator.mjs";
const API_VERSION = "1.3.0";
const DEFAULT_PORT = 31337;
const TOKEN_FILE = resolve(".matrix-cloud.env");
const MAX_BODY_BYTES = 512 * 1024;
let remoteApi;
let token;
let jobQueue = Promise.resolve();

function parseToken(text) {
  return text.match(/^MATRIX_GATEWAY_TOKEN=(.+)$/m)?.[1]?.trim();
}

async function loadToken() {
  if (process.env.MATRIX_GATEWAY_TOKEN) return process.env.MATRIX_GATEWAY_TOKEN;
  if (existsSync(TOKEN_FILE)) {
    const savedToken = parseToken(await readFile(TOKEN_FILE, "utf8"));
    if (savedToken) return savedToken;
  }
  const generatedToken = randomBytes(32).toString("base64url");
  await writeFile(TOKEN_FILE, `MATRIX_GATEWAY_TOKEN=${generatedToken}\n`, { encoding: "utf8", mode: 0o600 });
  console.log(`Created private cloud gateway token at ${TOKEN_FILE}`);
  return generatedToken;
}

function json(response, status, value) {
  response.writeHead(status, { "Content-Type": "application/json; charset=utf-8", "Cache-Control": "no-store", "X-Content-Type-Options": "nosniff" });
  response.end(JSON.stringify(value));
}

function requestToken(request) {
  const authorization = request.headers.authorization;
  if (typeof authorization === "string" && authorization.startsWith("Bearer ")) return authorization.slice(7);
  const headerToken = request.headers["x-matrix-token"];
  return typeof headerToken === "string" ? headerToken : undefined;
}

function authorized(request) {
  const candidate = requestToken(request);
  if (!candidate || !token) return false;
  const expected = Buffer.from(token);
  const received = Buffer.from(candidate);
  return expected.length === received.length && timingSafeEqual(expected, received);
}

function requireRemoteApi(response) {
  if (!remoteApi?.connection?.connected) {
    json(response, 503, { error: "Bitburner is not connected to the local Remote API." });
    return false;
  }
  return true;
}

function validServer(value) {
  return typeof value === "string" && /^[A-Za-z0-9._-]{1,64}$/.test(value);
}

function validFilename(value) {
  return typeof value === "string" && value.length > 0 && value.length <= 240 && !value.includes("\\") && !value.split("/").includes("..");
}

async function readBody(request) {
  const chunks = [];
  let bytes = 0;
  for await (const chunk of request) {
    bytes += chunk.length;
    if (bytes > MAX_BODY_BYTES) throw new Error("Request body is too large.");
    chunks.push(chunk);
  }
  return bytes === 0 ? {} : JSON.parse(Buffer.concat(chunks).toString("utf8"));
}

function openApiDocument(publicUrl) {
  return {
    openapi: "3.1.0",
    info: { title: "Bitburner Cloud Gateway", version: API_VERSION, description: "Authenticated gateway to one running Bitburner instance. Read before write; only write files or queue explicitly requested jobs." },
    servers: [{ url: publicUrl ?? "https://REPLACE-WITH-YOUR-TUNNEL-URL" }],
    components: { schemas: {}, securitySchemes: { MatrixToken: { type: "apiKey", in: "header", name: "X-Matrix-Token", description: "Private token generated by the local Bitburner gateway." } } },
    security: [{ MatrixToken: [] }],
    paths: {
      "/v1/status": { get: { operationId: "getBitburnerStatus", summary: "Check whether Bitburner is connected", responses: { "200": { description: "Gateway status" } } } },
      "/v1/operator/briefing": {get:{operationId:"getOperatorBriefing",summary:"Read facts and signed pause, resume, faction reputation or automatic policy options",responses:{"200":{description:"Observation and executable option tickets"},"409":{description:"Stale evidence"}}}},
      "/v1/operator/commands": {post:{operationId:"submitOperatorChoice",summary:"Submit the exact chosen ticket; retry the same ticket after ambiguity",requestBody:{required:true,content:{"application/json":{schema:{type:"object",additionalProperties:false,required:["ticket"],properties:{ticket:{type:"string",maxLength:2048}}}}}},responses:{"202":{description:"Queued or replayed; inspect the operation receipt"},"409":{description:"Expired, unavailable or previous-reset option"}}}},
      "/v1/operator/receipt": {get:{operationId:"getOperatorReceipt",summary:"Distinguish dispatch, control acceptance and scoped completion",parameters:[{name:"id",in:"query",required:true,schema:{type:"string"}},{name:"resetEpoch",in:"query",required:true,schema:{type:"string"}}],responses:{"200":{description:"Durable operation evidence"},"409":{description:"Reset changed or evidence unavailable"}}}},
      "/v1/servers": { get: { operationId: "listBitburnerServers", summary: "List servers visible to Bitburner", responses: { "200": { description: "Server list" } } } },
      "/v1/files": { get: { operationId: "listBitburnerFiles", summary: "List files on one server", parameters: [{ name: "server", in: "query", required: true, schema: { type: "string" } }], responses: { "200": { description: "File names" } } } },
      "/v1/file": {
        get: { operationId: "readBitburnerFile", summary: "Read one Bitburner file", parameters: [{ name: "server", in: "query", required: true, schema: { type: "string" } }, { name: "path", in: "query", required: true, schema: { type: "string" } }], responses: { "200": { description: "File content" } } },
        put: { operationId: "writeBitburnerFile", summary: "Create or replace one Bitburner file", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["server", "path", "content"], properties: { server: { type: "string" }, path: { type: "string" }, content: { type: "string" } } } } } }, responses: { "200": { description: "Write result" } } },
        delete: { operationId: "deleteBitburnerFile", summary: "Delete one Bitburner file", parameters: [{ name: "server", in: "query", required: true, schema: { type: "string" } }, { name: "path", in: "query", required: true, schema: { type: "string" } }], responses: { "200": { description: "Delete result" } } },
      },
      "/v1/ram": { get: { operationId: "calculateBitburnerRam", summary: "Ask the game itself what a script costs in RAM", parameters: [{ name: "server", in: "query", required: false, schema: { type: "string", default: "home" } }, { name: "path", in: "query", required: true, schema: { type: "string" } }], responses: { "200": { description: "RAM cost in GB" } } } },
      "/v1/agent": {get:{operationId:"getAgentHeartbeat",summary:"Read agent liveness and Home processes",responses:{"200":{description:"Agent heartbeat with freshness flag"}}}},
      "/v1/briefing": {get:{operationId:"getCurrentBriefing",summary:"Read the current reset briefing; expired reports are rejected",responses:{"200":{description:"Current operational briefing"},"409":{description:"Expired or previous-reset evidence"}}}},
      "/v1/jobs": { get:{operationId:"getJobReceipts",summary:"Read durable command receipts; started is not task completion",responses:{"200":{description:"Agent journal"}}}, post: { operationId: "queueBitburnerJob", summary: "Queue a run, kill, or killall command for the in-game cloud agent", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["action"], properties: { action: { type: "string", enum: ["run", "kill", "killall"] }, script: { type: "string" }, threads: { type: "integer", minimum: 1 }, args: { type: "array", maxItems:64, items: { type: ["string","number","boolean"] } }, server: { type: "string" }, idempotencyKey: {type:"string",pattern:"^[A-Za-z0-9_:-]{1,96}$",description:"Stable key per logical command. Never retry an ambiguous command with a new key."} } } } } }, responses: { "202": { description: "Job queued" } } } },
    },
  };
}

async function enqueueJob(command) {
  let queued;
  jobQueue = jobQueue.catch(() => undefined).then(async () => {
    const names = (await remoteApi.getFileNames("home")).result;
    let commands = [];
    if (names.some(name => name.replace(/^\/+/, "") === "cloud/commands.json")) {
      commands = JSON.parse((await remoteApi.getFile({server:"home", filename:"/cloud/commands.json"})).result);
      if (!Array.isArray(commands)) throw new Error("Invalid command queue");
    }
    const previous = commands.find(c => c.id === command.id);
    if (previous) {
      if (JSON.stringify([previous.action,previous.script,previous.server,previous.threads,previous.args,previous.resetEpoch]) !== JSON.stringify([command.action,command.script,command.server,command.threads,command.args,command.resetEpoch])) throw new Error("Invalid idempotency conflict");
      queued = previous; return;
    }
    const now = Date.now();
    commands = commands.filter(c => c.schemaVersion === 2 && c.expiresAt > now && c.resetEpoch === command.resetEpoch);
    if (commands.length >= 100) throw new Error("Command queue full; retry after expiry");
    commands.push(command);
    await remoteApi.pushFile({server:"home",filename:"/cloud/commands.json",content:JSON.stringify(commands)});
    queued = command;
  });
  await jobQueue;
  return queued;
}

export function setRemoteApi(api) {
  remoteApi = api;
  console.log("Bitburner Remote API connected; cloud gateway is ready.");
}

export async function startGateway({ port = Number(process.env.MATRIX_GATEWAY_PORT ?? DEFAULT_PORT) } = {}) {
  token = await loadToken();
  const operator = createOperator({secret:token,enqueue:enqueueJob,
    readRam:async filename=>(await remoteApi.calculateRAM({filename,server:"home"})).result,
    readJson:async (filename,...fallback)=>{
      if (fallback.length) {
        const names=(await remoteApi.getFileNames("home")).result;
        if (!names.some(name=>name.replace(/^\/+/,"")===filename.replace(/^\/+/,""))) return fallback[0];
      }
      return JSON.parse((await remoteApi.getFile({server:"home",filename})).result);
    }});
  const server = createServer(async (request, response) => {
    const url = new URL(request.url ?? "/", "http://127.0.0.1");
    const isSpec = request.method === "GET" && url.pathname === "/openapi.json";
    if (!isSpec && !authorized(request)) return json(response, 401, { error: "Use Authorization: Bearer <MATRIX_GATEWAY_TOKEN>." });
    try {
      if (isSpec) {
        const protocol = process.env.MATRIX_GATEWAY_PUBLIC_URL ? undefined : request.headers["x-forwarded-proto"] ?? "http";
        const publicUrl = process.env.MATRIX_GATEWAY_PUBLIC_URL ?? `${protocol}://${request.headers.host}`;
        return json(response, 200, openApiDocument(publicUrl));
      }
      if (request.method === "GET" && url.pathname === "/v1/status") return json(response, 200, { version: API_VERSION, bitburnerConnected: Boolean(remoteApi?.connection?.connected), commandAgent: "/cloud/agent.js" });
      if (!requireRemoteApi(response)) return;
      if (request.method === "GET" && url.pathname === "/v1/operator/briefing") return json(response,200,await operator.briefing());
      if (request.method === "POST" && url.pathname === "/v1/operator/commands") return json(response,202,await operator.submit(await readBody(request)));
      if (request.method === "GET" && url.pathname === "/v1/operator/receipt") return json(response,200,await operator.receipt(url.searchParams.get("id"),url.searchParams.get("resetEpoch")));
      if (request.method === "GET" && url.pathname === "/v1/agent") {
        const heartbeat = JSON.parse((await remoteApi.getFile({server:"home",filename:"/cloud/heartbeat.txt"})).result);
        return json(response, 200, { ...heartbeat, fresh: Number.isFinite(heartbeat.updated) && heartbeat.updated <= Date.now() && Date.now()-heartbeat.updated < 10000 });
      }
      if (request.method === "GET" && url.pathname === "/v1/jobs") {
        const journal = JSON.parse((await remoteApi.getFile({server:"home",filename:"/cloud/agent-journal.txt"})).result);
        return json(response, 200, journal);
      }
      if (request.method === "GET" && url.pathname === "/v1/briefing") {
        const report = JSON.parse((await remoteApi.getFile({server:"home",filename:"/matrix/state/briefing.txt"})).result);
        const heartbeat = JSON.parse((await remoteApi.getFile({server:"home",filename:"/cloud/heartbeat.txt"})).result);
        requireFreshReport(report,heartbeat);
        return json(response, 200, report);
      }
      if (request.method === "GET" && url.pathname === "/v1/servers") return json(response, 200, { servers: (await remoteApi.getAllServers()).result });
      if (request.method === "GET" && url.pathname === "/v1/files") {
        const serverName = url.searchParams.get("server");
        if (!validServer(serverName)) throw new Error("A valid server query parameter is required.");
        return json(response, 200, { server: serverName, files: (await remoteApi.getFileNames(serverName)).result });
      }
      if (request.method === "GET" && url.pathname === "/v1/ram") {
        const serverName = url.searchParams.get("server") ?? "home";
        const filename = url.searchParams.get("path");
        if (!validServer(serverName) || !validFilename(filename)) throw new Error("Valid server and path query parameters are required.");
        const reply = await remoteApi.calculateRAM({ filename, server: serverName });
        return json(response, 200, { server: serverName, path: filename, ram: reply.result });
      }
      if (request.method === "GET" && url.pathname === "/v1/file") {
        const serverName = url.searchParams.get("server");
        const filename = url.searchParams.get("path");
        if (!validServer(serverName) || !validFilename(filename)) throw new Error("Valid server and path query parameters are required.");
        return json(response, 200, { server: serverName, path: filename, content: (await remoteApi.getFile({ server: serverName, filename })).result });
      }
      if (request.method === "PUT" && url.pathname === "/v1/file") {
        const { server: serverName, path: filename, content } = await readBody(request);
        if (!validServer(serverName) || !validFilename(filename) || typeof content !== "string") throw new Error("server, path, and string content are required.");
        return json(response, 200, { result: (await remoteApi.pushFile({ server: serverName, filename, content })).result });
      }
      if (request.method === "DELETE" && url.pathname === "/v1/file") {
        const serverName = url.searchParams.get("server");
        const filename = url.searchParams.get("path");
        if (!validServer(serverName) || !validFilename(filename)) throw new Error("Valid server and path query parameters are required.");
        return json(response, 200, { result: (await remoteApi.deleteFile({ server: serverName, filename })).result });
      }
      if (request.method === "POST" && url.pathname === "/v1/jobs") {
        const job = await readBody(request);
        const heartbeat = JSON.parse((await remoteApi.getFile({server:"home",filename:"/cloud/heartbeat.txt"})).result);
        const normalized = normalizeJob(job, heartbeat);
        const id = job.idempotencyKey ? createHash("sha256").update(`${heartbeat.resetEpoch}:${job.idempotencyKey}`).digest("hex") : randomBytes(12).toString("hex");
        const command = { ...normalized, id, createdAt: new Date().toISOString() };
        const queued = await enqueueJob(command);
        return json(response, 202, { queued: true, id: queued.id, commandFile: "/cloud/commands.json" });
      }
      return json(response, 404, { error: "Unknown endpoint." });
    } catch (error) {
      if (error instanceof OperatorError) return json(response,error.status,{error:error.message});
      const message = error instanceof Error ? error.message : String(error?.error ?? error ?? "Unexpected gateway error");
      const invalidRequest = message.includes("too large") || message.includes("JSON") || message.includes("required") || message.startsWith("Invalid") || message.startsWith("action") || message.startsWith("threads") || message.startsWith("args");
      return json(response, invalidRequest ? 400 : 502, { error: message });
    }
  });
  await new Promise((resolveStart, rejectStart) => server.once("error", rejectStart).listen(port, "127.0.0.1", resolveStart));
  console.log(`Cloud gateway listening privately at http://127.0.0.1:${port}`);
  return server;
}

if (process.argv.includes("--print-token")) {
  token = await loadToken();
  console.log(token);
  process.exit(0);
}
